### ISSUE TITLE
DPI getting nuked

### ISSUE THREAD

**Issue by thro86** [ItsGoldeneyes/mpc-bleed-edge-editor#1]
Card Details prior to Save Image
672xx936
297 DPI

Card Details post Save Image
750x1014
96 DPI

The issue now is that when I go to upload this image into Makeplayingcards it gives a LOW RESOLUTION warning. What, if anything, can be done to preserve the DPI of the card?

**Comment by ItsGoldeneyes** [comment]
Forced 800 dpi in commit #f8b23e7. Should fix the issue until I get around to rewriting the program
